In [20]:
# Library installation for project

import pandas as pd
import numpy as np

import platform
import pyodbc

from sqlalchemy.engine import URL
from sqlalchemy import create_engine, text

import matplotlib.pyplot as plt
import dtale
import sweetviz
# import pandas_profiling

import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats

pd.set_option('display.max_columns', None)

In [21]:
import os

# Change the current working directory
os.chdir('C:/Users/DeepankarSrigyan/OneDrive - Sykes Cottages Ltd/Desktop/Project/Picture Vs Revnues/')

# Now, when you open a file without specifying a full path, Python looks in the current working directory
with open('another_file.txt', 'w') as f:
    f.write('This file is saved in the specified default directory.')

In [17]:
import psycopg2

# Define the connection parameters
dbname = 'workgroup'
user = 'readonly'
password = 'xgrWX!Qp.NG4xw'
host = 'tableau.sykes.network'  # Or the hostname where your Tableau Server is running
port = '8060'  # Default Tableau repository port

# Establish a connection to the Tableau repository database
try:
    conn = psycopg2.connect(dbname=dbname, user=user, password=password, host=host, port=port)
    print("Connected to the Tableau repository successfully!")

except psycopg2.Error as e:
    print("Unable to connect to the Tableau repository:", e)

Connected to the Tableau repository successfully!

In [18]:
import pandas as pd

def execute_query(query):
    """
    Execute an SQL query on the Tableau repository database and return results in a DataFrame.
    
    Parameters:
    query (str): The SQL query to execute.
    
    Returns:
    pd.DataFrame: DataFrame containing the query results.
    """
    # Create a cursor object to interact with the database
    cur = conn.cursor()
    
    try:
        # Execute the query
        cur.execute(query)
        rows = cur.fetchall()

        # Get column names
        columns = [desc[0] for desc in cur.description]

        # Convert rows and columns into DataFrame
        df = pd.DataFrame(rows, columns=columns)

        return df

    except psycopg2.Error as e:
        print("Error executing the query:", e)
        
    finally:
        # Close the cursor
        cur.close()

In [19]:
# Example usage:
query = """with hist_event_data as
(
SELECT 
-- 	"desktop_reporting"."action" AS "action",
-- 	"desktop_reporting"."action_key" AS "action_key",
	CAST("historical_event_types"."action_type" AS TEXT) AS "action_type",
-- 	"desktop_reporting"."app_version" AS "app_version",
-- 	CAST("hist_datasources"."certification_note" AS TEXT) AS "certification_note",
-- 	CAST("hist_comments"."comment" AS TEXT) AS "comment",
-- 	"hist_comments"."comment_id" AS "comment_id",
-- 	"desktop_reporting"."company" AS "company",
-- 	"desktop_reporting"."computer_user_id" AS "computer_user_id",
	"historical_events"."created_at" AS "created_at",
-- 	"hist_datasources"."datasource_id" AS "datasource_id",
-- 	"desktop_reporting"."department" AS "department",
-- 	CAST("historical_events"."details" AS TEXT) AS "details",
-- 	"desktop_reporting"."domain" AS "domain",
	CAST("hist_users"."domain_name" AS TEXT) AS "domain_name",
-- 	"historical_events"."duration_in_ms" AS "duration_in_ms",
-- 	"desktop_reporting"."edition" AS "edition",
-- 	"desktop_reporting"."email" AS "email (desktop_reporting)",
	CAST("hist_users"."email" AS TEXT) AS "email",
-- 	"desktop_reporting"."expiration_date" AS "expiration_date",
-- 	"desktop_reporting"."first_name" AS "first_name",
-- 	"historical_events"."hist_actor_site_id" AS "hist_actor_site_id",
-- 	"historical_events"."hist_actor_user_id" AS "hist_actor_user_id",
-- 	"historical_events"."hist_capability_id" AS "hist_capability_id",
-- 	"historical_events"."hist_collection_id" AS "hist_collection_id",
-- 	"historical_events"."hist_column_id" AS "hist_column_id",
-- 	"historical_events"."hist_comment_id" AS "hist_comment_id",
-- 	"historical_events"."hist_config_id" AS "hist_config_id",
-- 	"historical_events"."hist_data_connection_id" AS "hist_data_connection_id",
-- 	"historical_events"."hist_data_quality_indicator_id" AS "hist_data_quality_indicator_id",
-- 	"historical_events"."hist_data_role_id" AS "hist_data_role_id",
-- 	"historical_events"."hist_database_id" AS "hist_database_id",
-- 	"historical_events"."hist_datasource_id" AS "hist_datasource_id",
-- 	"historical_events"."hist_flow_draft_id" AS "hist_flow_draft_id",
-- 	"historical_events"."hist_flow_id" AS "hist_flow_id",
-- 	"historical_events"."hist_group_id" AS "hist_group_id",
-- 	"hist_users"."hist_licensing_role_id" AS "hist_licensing_role_id (hist_users)",
-- 	"historical_events"."hist_licensing_role_id" AS "hist_licensing_role_id",
-- 	"historical_events"."hist_metric_id" AS "hist_metric_id",
	"historical_events"."hist_project_id" AS "hist_project_id",
-- 	"historical_events"."hist_published_connection_id" AS "hist_published_connection_id",
-- 	"historical_events"."hist_remote_agent_id" AS "hist_remote_agent_id",
-- 	"historical_events"."hist_schedule_id" AS "hist_schedule_id",
-- 	"historical_events"."hist_table_id" AS "hist_table_id",
-- 	"historical_events"."hist_tag_id" AS "hist_tag_id",
	"historical_events"."hist_target_site_id" AS "hist_target_site_id",
-- 	"historical_events"."hist_target_user_id" AS "hist_target_user_id",
-- 	"historical_events"."hist_task_id" AS "hist_task_id",
	"historical_events"."hist_view_id" AS "hist_view_id",
	"historical_events"."hist_workbook_id" AS "hist_workbook_id",
	"historical_events"."historical_event_type_id" AS "historical_event_type_id",
-- 	"desktop_reporting"."host_name" AS "host_name",
-- 	"desktop_reporting"."id" AS "id (desktop_reporting)",
-- 	"hist_comments"."id" AS "id (hist_comments)",
-- 	"hist_datasources"."id" AS "id (hist_datasources)",
	"hist_projects"."id" AS "id (hist_projects)",
	"hist_sites"."id" AS "id (hist_sites)",
	"hist_users"."id" AS "id (hist_users)",
	"hist_views"."id" AS "id (hist_views)",
	"hist_workbooks"."id" AS "id (hist_workbooks)",
	"historical_events"."id" AS "id",
-- 	"hist_datasources"."is_certified" AS "is_certified",
	"historical_events"."is_failure" AS "is_failure",
-- 	"desktop_reporting"."last_name" AS "last_name",
-- 	"desktop_reporting"."last_report_date" AS "last_report_date",
-- 	"desktop_reporting"."mac_address" AS "mac_address",
-- 	"desktop_reporting"."maintenance_expiration" AS "maintenance_expiration",
-- 	CAST("hist_datasources"."name" AS TEXT) AS "name (hist_datasources)",
	CAST("hist_projects"."name" AS TEXT) AS "name (hist_projects)",
	CAST("hist_sites"."name" AS TEXT) AS "name (hist_sites)",
	CAST("hist_users"."name" AS TEXT) AS "name (hist_users)",
	CAST("hist_views"."name" AS TEXT) AS "name (hist_views)",
	CAST("hist_workbooks"."name" AS TEXT) AS "name (hist_workbooks)",
	CAST("historical_event_types"."name" AS TEXT) AS "name",
	"desktop_reporting"."os_architecture" AS "os_architecture",
-- 	"desktop_reporting"."os_version" AS "os_version",
-- 	"desktop_reporting"."product_keys" AS "product_keys",
-- 	"desktop_reporting"."product_name" AS "product_name",
	"hist_projects"."project_id" AS "project_id",
-- 	"hist_users"."publisher_tristate" AS "publisher_tristate",
-- 	"desktop_reporting"."registration_date" AS "registration_date",
-- 	CAST("hist_datasources"."remote_query_agent_name" AS TEXT) AS "remote_query_agent_name",
	CAST("hist_views"."repository_url" AS TEXT) AS "repository_url (hist_views)",
-- 	CAST("hist_workbooks"."repository_url" AS TEXT) AS "repository_url (hist_workbooks)",
	CAST("hist_datasources"."repository_url" AS TEXT) AS "repository_url",
	CAST("hist_views"."revision" AS TEXT) AS "revision (hist_views)",
	CAST("hist_workbooks"."revision" AS TEXT) AS "revision (hist_workbooks)",
-- 	CAST("hist_datasources"."revision" AS TEXT) AS "revision",
-- 	"desktop_reporting"."serial_number" AS "serial_number",
-- 	"hist_users"."site_admin_level" AS "site_admin_level",
	"hist_sites"."site_id" AS "site_id",
	"hist_users"."site_role_id" AS "site_role_id",
	"hist_workbooks"."size" AS "size (hist_workbooks)"
-- 	"hist_datasources"."size" AS "size",
-- 	"hist_users"."system_admin_level" AS "system_admin_level",
-- 	"hist_users"."system_user_id" AS "system_user_id",
-- 	"desktop_reporting"."type" AS "type",
-- 	"historical_event_types"."type_id" AS "type_id",
-- 	"desktop_reporting"."unique_machine_number" AS "unique_machine_number",
-- 	CAST("hist_sites"."url_namespace" AS TEXT) AS "url_namespace",
-- 	"hist_users"."user_id" AS "user_id",
-- 	"hist_datasources"."using_remote_query_agent" AS "using_remote_query_agent",
-- 	"hist_views"."view_id" AS "view_id",
-- 	"hist_workbooks"."workbook_id" AS "workbook_id",
-- 	CAST("historical_events"."worker" AS TEXT) AS "worker"
FROM "public"."historical_events" "historical_events"
INNER JOIN "public"."historical_event_types" "historical_event_types" ON ("historical_events"."historical_event_type_id" = "historical_event_types"."type_id")
LEFT JOIN "public"."hist_datasources" "hist_datasources" ON ("historical_events"."hist_datasource_id" = "hist_datasources"."id")
LEFT JOIN "public"."hist_workbooks" "hist_workbooks" ON ("historical_events"."hist_workbook_id" = "hist_workbooks"."id")
LEFT JOIN "public"."hist_users" "hist_users" ON ("historical_events"."hist_actor_user_id" = "hist_users"."id")
LEFT JOIN "public"."hist_views" "hist_views" ON ("historical_events"."hist_view_id" = "hist_views"."id")
LEFT JOIN "public"."hist_sites" "hist_sites" ON ("historical_events"."hist_actor_site_id" = "hist_sites"."id")
LEFT JOIN "public"."hist_comments" "hist_comments" ON ("historical_events"."hist_comment_id" = "hist_comments"."id")
LEFT JOIN "public"."hist_projects" "hist_projects" ON ("historical_events"."hist_project_id" = "hist_projects"."id")
LEFT JOIN "public"."desktop_reporting" "desktop_reporting" ON ("historical_events"."id" = "desktop_reporting"."id")


	)
	select * from hist_event_data"""
Tableau_Data = execute_query(query)
Tableau_Data

,action_type,created_at,domain_name,email,hist_project_id,hist_target_site_id,hist_view_id,hist_workbook_id,historical_event_type_id,id (hist_projects),...,name,os_architecture,project_id,repository_url (hist_views),repository_url,revision (hist_views),revision (hist_workbooks),site_id,site_role_id,size (hist_workbooks)
0,Access,2023-12-31 01:27:45.002,sykescottages.co.uk,william.yates@sykescottages.co.uk,162.0,3.0,NaN,NaN,112,162.0,...,Access Data Source,None,125.0,None,ExperimentInfo,None,None,1.0,10.0,NaN
1,Access,2024-01-01 08:01:48.418,sykescottages.co.uk,joanna.bailey@sykescottages.co.uk,3.0,3.0,NaN,NaN,112,3.0,...,Access Data Source,None,4.0,None,KPI,None,None,1.0,9.0,NaN
2,Access,2024-01-01 08:01:48.864,sykescottages.co.uk,phil.pascoe@sykescottages.co.uk,14.0,3.0,NaN,NaN,112,14.0,...,Access Data Source,None,15.0,None,BookingsFinancials,None,None,1.0,9.0,NaN
3,Access,2024-01-01 08:01:49.693,sykescottages.co.uk,joanna.bailey@sykescottages.co.uk,3.0,3.0,NaN,NaN,112,3.0,...,Access Data Source,None,4.0,None,KPI,None,None,1.0,9.0,NaN
4,Access,2024-01-01 08:01:53.775,sykescottages.co.uk,alison.powell@sykescottages.co.uk,14.0,3.0,NaN,NaN,112,14.0,...,Access Data Source,None,15.0,None,PropertyRecruitmentTasks,None,None,1.0,9.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435401,Access,2023-12-30 23:55:09.652,sykescottages.co.uk,None,NaN,NaN,NaN,NaN,1,NaN,...,Login,None,NaN,None,None,None,None,1.0,10.0,NaN
1435402,Publish,2023-12-30 23:55:10.635,sykescottages.co.uk,None,20.0,3.0,NaN,NaN,110,20.0,...,Publish Data Source,None,21.0,None,ab_testing_summary_16976299368870,None,None,1.0,10.0,NaN
1435403,Access,2023-12-30 23:55:10.831,sykescottages.co.uk,None,NaN,NaN,NaN,NaN,2,NaN,...,Logout,None,NaN,None,None,None,None,1.0,10.0,NaN
1435404,Access,2023-12-31 00:38:12.149,sykescottages.co.uk,daniel.berry@sykescottages.co.uk,105.0,2.0,NaN,NaN,112,105.0,...,Access Data Source,None,91.0,None,KPIUAT,None,None,2.0,10.0,NaN
1435405,Access,2023-12-31 01:26:10.050,sykescottages.co.uk,daniel.berry@sykescottages.co.uk,66.0,3.0,NaN,NaN,112,66.0,...,Access Data Source,None,61.0,None,ParentNodeByBrandByTimeDev,None,None,1.0,10.0,NaN

In [22]:
Tableau_Data  = sweetviz.analyze(Tableau_Data)
Tableau_Data.show_html('Tableau_Data.html')

                                             |                                             | [  0%]   00:00 ->…

Report Tableau_Data.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.